/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sys/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll"];
        put: operations["update"];
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/userrole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll"];
        put: operations["update_1"];
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/userapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll_1"];
        put: operations["update_2"];
        post: operations["add_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll_2"];
        put: operations["update_4"];
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/rolepermission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_1"];
        put: operations["update_5"];
        post: operations["add_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll_3"];
        put: operations["update_6"];
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permissionmenu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put: operations["update_7"];
        post: operations["add_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permissionapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_2"];
        put: operations["update_8"];
        post: operations["add_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll_4"];
        put: operations["update_9"];
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put: operations["update_10"];
        post: operations["add_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/userrole/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/userrole/user/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRolesByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/userapp/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_2"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/user/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/template/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_3"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/rolepermission/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_4"];
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/role/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_5"];
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/role/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPermissionsByRoleId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/role/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["test_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/role/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageAll_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permissionmenu/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_6"];
        put?: never;
        post?: never;
        delete: operations["delete_6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permissionapi/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_7"];
        put?: never;
        post?: never;
        delete: operations["delete_7"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_8"];
        put?: never;
        post?: never;
        delete: operations["delete_8"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserPermissionsAndRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission/user/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUserPermissionsAndRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageAll_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/permission/appCodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAppCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/menu/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_9"];
        put?: never;
        post?: never;
        delete: operations["delete_9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/menu/user/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserMenuTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/menu/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenuTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sys/app/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_10"];
        put?: never;
        post?: never;
        delete: operations["delete_10"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SysUser: {
            /** Format: int64 */
            userId?: number;
            username?: string;
            email?: string;
            password?: string;
            fullName?: string;
            avatarUrl?: string;
            gender?: string;
            /** Format: date */
            birthDate?: string;
            status?: string;
            /** Format: date-time */
            lastLogin?: string;
            /** Format: int32 */
            loginAttempts?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
            emailVerified?: boolean;
            phoneVerified?: boolean;
            twoFactorEnabled?: boolean;
            isDeleted?: boolean;
        };
        ResponseResultSysUser: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUser"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysUserRole: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            roleId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ResponseResultSysUserRole: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUserRole"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysUserApp: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            appId?: number;
            /** Format: int32 */
            status?: number;
            /** Format: date-time */
            createTime?: string;
        };
        ResponseResultSysUserApp: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUserApp"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysTemplate: {
            /** Format: int64 */
            templateId?: number;
            templateName?: string;
            templateType?: string;
            templateContent?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
            isDeleted?: boolean;
            /** Format: int64 */
            creatorId?: number;
            /** Format: int64 */
            updaterId?: number;
            description?: string;
        };
        ResponseResultSysTemplate: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysTemplate"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysRole: {
            /** Format: int64 */
            id?: number;
            roleCode?: string;
            roleName?: string;
            status?: boolean;
            remark?: string;
            /** Format: int32 */
            deleted?: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        ResponseResultSysRole: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysRole"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysRolePermission: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            roleId?: number;
            /** Format: int64 */
            permissionId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ResponseResultBoolean: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: boolean;
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysPermission: {
            /** Format: int32 */
            id?: number;
            permissionKey?: string;
            name?: string;
            description?: string;
            type?: string;
            appCode?: string;
            status?: boolean;
            /** Format: int32 */
            parentId?: number;
            /** Format: int32 */
            isDeleted?: number;
            /** Format: int32 */
            priority?: number;
            /** Format: int32 */
            isSystem?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseResultSysPermission: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermission"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysPermissionMenu: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            permissionId?: number;
            /** Format: int64 */
            menuId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ResponseResultSysPermissionMenu: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermissionMenu"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysPermissionApi: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            permissionId?: number;
            systemCode?: string;
            httpMethod?: string;
            urlPattern?: string;
            apiVersion?: string;
            description?: string;
            /** Format: int32 */
            status?: number;
            needAuth?: boolean;
            requestContentType?: string;
            responseContentType?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseResultSysPermissionApi: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermissionApi"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysMenu: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            parentId?: number;
            menuName?: string;
            menuCode?: string;
            /** Format: int32 */
            menuType?: number;
            path?: string;
            component?: string;
            icon?: string;
            /** Format: int32 */
            sortOrder?: number;
            visible?: boolean;
            status?: boolean;
            remark?: string;
            /** Format: int64 */
            createdBy?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            updatedBy?: number;
            /** Format: date-time */
            updatedAt?: string;
            routerName?: string;
        };
        ResponseResultSysMenu: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysMenu"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        SysApp: {
            /** Format: int64 */
            id?: number;
            appCode?: string;
            appName?: string;
            /** Format: int32 */
            status?: number;
            remark?: string;
            /** Format: int32 */
            deleted?: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            username?: string;
            avatar?: string;
        };
        ResponseResultLoginResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysUser: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUser"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysUserRole: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUserRole"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysRole: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysRole"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysUserApp: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysUserApp"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultString: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: string;
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        OrderItem: {
            column?: string;
            asc?: boolean;
        };
        PageSysUser: {
            records?: components["schemas"]["SysUser"][];
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            current?: number;
            orders?: components["schemas"]["OrderItem"][];
            optimizeCountSql?: components["schemas"]["PageSysUser"];
            searchCount?: components["schemas"]["PageSysUser"];
            optimizeJoinOfCountSql?: boolean;
            /** Format: int64 */
            maxLimit?: number;
            countId?: string;
            /**
             * Format: int64
             * @deprecated
             */
            pages?: number;
        };
        ResponseResultPageSysUser: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageSysUser"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysRolePermission: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysRolePermission"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultSysRolePermission: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysRolePermission"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysPermission: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermission"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResult: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: unknown;
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        PageSysRole: {
            records?: components["schemas"]["SysRole"][];
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            current?: number;
            orders?: components["schemas"]["OrderItem"][];
            optimizeCountSql?: components["schemas"]["PageSysRole"];
            searchCount?: components["schemas"]["PageSysRole"];
            optimizeJoinOfCountSql?: boolean;
            /** Format: int64 */
            maxLimit?: number;
            countId?: string;
            /**
             * Format: int64
             * @deprecated
             */
            pages?: number;
        };
        ResponseResultPageSysRole: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageSysRole"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysPermissionMenu: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermissionMenu"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysPermissionApi: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysPermissionApi"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultUserPermissionsDTO: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserPermissionsDTO"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        UserPermissionsDTO: {
            /** Format: int64 */
            userId?: number;
            isSuperAdmin?: boolean;
            roles?: components["schemas"]["SysRole"][];
            permissions?: components["schemas"]["SysPermission"][];
        };
        PageSysPermission: {
            records?: components["schemas"]["SysPermission"][];
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            current?: number;
            orders?: components["schemas"]["OrderItem"][];
            optimizeCountSql?: components["schemas"]["PageSysPermission"];
            searchCount?: components["schemas"]["PageSysPermission"];
            optimizeJoinOfCountSql?: boolean;
            /** Format: int64 */
            maxLimit?: number;
            countId?: string;
            /**
             * Format: int64
             * @deprecated
             */
            pages?: number;
        };
        ResponseResultPageSysPermission: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageSysPermission"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListString: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: string[];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysMenu: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysMenu"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        MenuTreeModel: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            parentId?: number;
            menuName?: string;
            /** Format: int32 */
            level?: number;
            icon?: string;
            /** Format: int32 */
            sort?: number;
            path?: string;
            component?: string;
            /** Format: int32 */
            menuType?: number;
            visible?: boolean;
            permission?: string;
            routerName?: string;
            children?: components["schemas"]["MenuTreeModel"][];
        };
        ResponseResultListMenuTreeModel: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MenuTreeModel"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultListSysApp: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysApp"][];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultSysApp: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["SysApp"];
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
        ResponseResultVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: unknown;
            /** Format: int64 */
            timestamp?: number;
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysUser"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUser"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUser"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysUserRole"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUserRole"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserRole"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUserRole"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserRole"];
                };
            };
        };
    };
    listAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysUserApp"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUserApp"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserApp"];
                };
            };
        };
    };
    add_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysUserApp"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserApp"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysTemplate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysTemplate"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysTemplate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysTemplate"];
                };
            };
        };
    };
    listAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysRole"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysRole"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysRole"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysRole"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysRole"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysRolePermission"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysRolePermission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    add_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysRolePermission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    listAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysPermission"];
                };
            };
        };
    };
    update_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermission"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermission"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysPermissionMenu"];
                };
            };
        };
    };
    update_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermissionMenu"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionMenu"];
                };
            };
        };
    };
    add_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermissionMenu"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionMenu"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysPermissionApi"];
                };
            };
        };
    };
    update_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermissionApi"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionApi"];
                };
            };
        };
    };
    add_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysPermissionApi"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionApi"];
                };
            };
        };
    };
    listAll_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysMenu"];
                };
            };
        };
    };
    update_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysMenu"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysMenu"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysMenu"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysMenu"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysApp"];
                };
            };
        };
    };
    update_10: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysApp"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    add_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SysApp"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultLoginResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserRole"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getRolesByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysRole"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUserApp"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysUser"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultString"];
                };
            };
        };
    };
    pageAll: {
        parameters: {
            query: {
                pageNum: number;
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultPageSysUser"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysTemplate"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    getById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysRolePermission"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    getById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysRole"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getPermissionsByRoleId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListSysPermission"];
                };
            };
        };
    };
    test_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResult"];
                };
            };
        };
    };
    pageAll_1: {
        parameters: {
            query: {
                pageNum: number;
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultPageSysRole"];
                };
            };
        };
    };
    getById_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionMenu"];
                };
            };
        };
    };
    delete_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getById_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermissionApi"];
                };
            };
        };
    };
    delete_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
    getById_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysPermission"];
                };
            };
        };
    };
    delete_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getUserPermissionsAndRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultUserPermissionsDTO"];
                };
            };
        };
    };
    getCurrentUserPermissionsAndRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultUserPermissionsDTO"];
                };
            };
        };
    };
    pageAll_2: {
        parameters: {
            query: {
                pageNum: number;
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultPageSysPermission"];
                };
            };
        };
    };
    getAppCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListString"];
                };
            };
        };
    };
    getById_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysMenu"];
                };
            };
        };
    };
    delete_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultVoid"];
                };
            };
        };
    };
    getUserMenuTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListMenuTreeModel"];
                };
            };
        };
    };
    getMenuTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultListMenuTreeModel"];
                };
            };
        };
    };
    getById_10: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultSysApp"];
                };
            };
        };
    };
    delete_10: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseResultBoolean"];
                };
            };
        };
    };
}
